#### Jonathan Lynch
#### CSC 578/Section 901
#### Homework 3 (578hw3.ipynb)

In [3]:
import NN578_networkI as network
import numpy as np
import random
import matplotlib.pyplot as plt

In [4]:
# Load the dataset (already in the 'one-hot-vector' format for the target)
# Call the function to load the data.
iris_data = network.my_load_csv('iris.csv', 4, 3)

OSError: iris.csv not found.

### A) Check network definition code which includes the Modifications described in Part 2 of HW3:

__Train the net1 network (created from iris-423.dat) on the iris data for a maximum of 100 epochs, minibatch_size=5, eta=0.5:__

In [6]:
# Create a network from the saved network
net1 = network.load_network("iris-423.dat")

# Train the network for 100 epochs, with minibatch size 5, eta=0.5 and no testset. 
results1 = net1.SGD(iris_data, 1, 1, 0.5)

[[-0.08325485 -0.00832208]
 [ 0.13403796  0.01339831]
 [ 0.05432188  0.00542996]]
[[-0.0770944  -0.00758026]
 [ 0.12993123  0.01277542]
 [ 0.05114263  0.00502857]]
[[-0.07190015 -0.00806979]
 [ 0.11798564  0.01324224]
 [ 0.0472298   0.00530088]]
[[-0.06654346 -0.00539224]
 [ 0.1112287   0.00901324]
 [ 0.04570911  0.00370396]]
[[-0.06219481 -0.00608757]
 [ 0.10378746  0.01015862]
 [ 0.04256813  0.00416653]]
[[-0.05684865 -0.00247766]
 [ 0.10133669  0.00441661]
 [ 0.04237795  0.00184698]]
[[-0.05466995 -0.0043581 ]
 [ 0.08742849  0.0069695 ]
 [ 0.03872024  0.00308664]]
[[-0.05056227 -0.00425491]
 [ 0.08530153  0.00717829]
 [ 0.03670552  0.00308884]]
[[-0.04819926 -0.00455067]
 [ 0.07653709  0.00722615]
 [ 0.0346193   0.00326854]]
[[-0.04477454 -0.00450768]
 [ 0.07400571  0.00745053]
 [ 0.03279644  0.00330178]]
[[-0.04188006 -0.00370947]
 [ 0.06980165  0.00618258]
 [ 0.03165423  0.00280373]]
[[-0.04018272 -0.00288648]
 [ 0.06267477  0.00450216]
 [ 0.03082339  0.00221416]]
[[-0.03811985 -0

__Create another network by reloading the same saved network and train the network with the same three hyperparameter values, and stopaccuracy=0.75:__

In [4]:
# Create a network from the saved network
net2 = network.load_network("iris-423.dat")

# Train the net2 network for 100 epochs, minibatch size 5, eta=0.5, stopaccuracy=0.75, and no testset 
results2 = net2.SGD(iris_data, 100, 5, 0.5, stopaccuracy=0.75)

[[0.95367519]
 [0.09532847]]
--------
[[-0.08729895]
 [ 0.14054885]
 [ 0.05696056]]
------
[[0.96232764]
 [0.09462034]]
--------
[[-0.08011242]
 [ 0.13501766]
 [ 0.05314472]]
------
[[0.9346247 ]
 [0.10489854]]
--------
[[-0.07692943]
 [ 0.12623852]
 [ 0.05053344]]
------
[[0.93904845]
 [0.07609427]]
--------
[[-0.07086264]
 [ 0.11844831]
 [ 0.04867599]]
------
[[0.93770311]
 [0.09178149]]
--------
[[-0.06632677]
 [ 0.11068265]
 [ 0.04539617]]
------
[[0.97040953]
 [0.04229384]]
--------
[[-0.05858212]
 [ 0.10442673]
 [ 0.04367017]]
------
[[0.92676976]
 [0.07387886]]
--------
[[-0.05898979]
 [ 0.0943368 ]
 [ 0.04177978]]
------
[[0.95456688]
 [0.08032863]]
--------
[[-0.0529688 ]
 [ 0.08936151]
 [ 0.03845254]]
------
[[0.93559171]
 [0.08833269]]
--------
[[-0.0515174 ]
 [ 0.08180608]
 [ 0.03700258]]
------
[[0.95761586]
 [0.09640802]]
--------
[[-0.04675626]
 [ 0.07728121]
 [ 0.03424801]]
------
[[0.96772899]
 [0.08571519]]
--------
[[-0.04327664]
 [ 0.07212934]
 [ 0.03270981]]
------

### B) Check code with a different, deeper network, in particular the 4-20-7-3 network:

__Create a new network by loading the saved 4-20-7-3 network, then train the network using the same hyperparameters (epochs=100, minibatch_size=5, eta=0.5, stopaccuracy=0.75):__

In [5]:
# Create a network from the saved network 4-20-7-3:
net3 = network.load_network("iris4-20-7-3.dat")

# Train the net3 network for 100 epochs, minibatch size 5, eta=0.5, stopaccuracy=0.75, and no testset
results3 = net3.SGD(iris_data, 100, 5, 0.5, stopaccuracy=0.75)

FileNotFoundError: [Errno 2] No such file or directory: 'iris4-20-7-3.dat'

### C) Visualize the network learning by creating plots:

   __A. First split the dataset randomly into 70% training and 30% test:__

In [ ]:
iris_data
random.shuffle(iris_data)
training = iris_data[0:105] # first 70% of the iris_data 
test = iris_data[-45:]      # last 30% of the iris_data

__B. Create a new network (which has randomly initialized weights) of the size [4,20,3]:__

In [ ]:
# Create a new network net4
net4 = network.Network([4,20,3])

__C. Train the network for 50 epochs with eta = 0.1 and the minibatch size = 5 (default for stopaccuracy), and save results:__

In [ ]:
results4 = net4.SGD(training, 50, 5, 0.1, test)

__D. Use results to plot two types of graphs:__

__D-A. Plot that compares the error curves of the three cost functions for the training set:__ 

In [ ]:
MSE = []
CE = []
LL = []

for res in results4[0]:
    MSE.append(res[2])
    CE.append(res[3])
    LL.append(res[4])
    
plt.plot(MSE, c='red', label='MSE')
plt.plot(CE, c='green', label='CrossEntropy')
plt.plot(LL, c='blue', label='LogLikelihood')
plt.legend()
plt.ylabel('Error')
plt.xlabel('Epoch')
plt.title('Error by Cost Function (training)')

plt.show()

__D-B. Three plots, one for each cost function, that shows the error for training vs. test:__

In [ ]:
test_MSE = []
test_CE = []
test_LL = []

for res in results4[1]:
    test_MSE.append(res[2])
    test_CE.append(res[3])
    test_LL.append(res[4])

In [ ]:
plt.plot(MSE, c='red', label='Train')
plt.plot(test_MSE, c='gold', label='Test')
plt.legend()
plt.ylabel('Error')
plt.xlabel('Epoch')
plt.title('Train vs Test: MSE')

plt.show()

In [ ]:
plt.plot(CE, c='green', label='Train')
plt.plot(test_CE, c='gold', label='Test')
plt.legend()
plt.ylabel('Error')
plt.xlabel('Epoch')
plt.title('Train vs Test: CrossEntropy')

plt.show()

In [ ]:
plt.plot(LL, c='blue', label='Train')
plt.plot(test_LL, c='gold', label='Test')
plt.legend()
plt.ylabel('Error')
plt.xlabel('Epoch')
plt.title('Train vs Test: LogLikelihood')

plt.show()